apiVersion: v1
kind: Service
metadata: 
  name: main-service
spec:
  ports:
    - protocol: TCP
      name: server-join-port
      port: 25565
      targetPort: 25565
    - protocol: TCP
      name: console-port
      port: 25500 
      targetPort: 25500
    - protocol: TCP
      name: keyshit
      port: 80
      targetPort: 80
